### ISSUE TITLE
constant.ts

### ISSUE THREAD

**Issue by wy10cheng** [alikhan866/Casbin-Role-Mgt-Dashboard-RBAC#4]
Hi,

I had tried to insert the database details to start the app but it does not work. Could you please help?

**Comment by alikhan866** [comment]
Hi , 

1 ) Did you try deploying using a local database to check if that works ? 

2 ) What does not work ?

3) Please post the error message 

4) Also make sure you are entering mysql credentials only since this project does not support any other databases as of now ( I have plans to integrate more DB in future )

**Comment by alikhan866** [comment]
As discussed in facebook it was a mySql access issue and hence not relevant to this project.

It was solved by creating a new user with all rights in mysql.

```
CREATE USER 'usernamehere'@'localhost' IDENTIFIED BY 'passwordhere';
GRANT ALL PRIVILEGES ON * . * TO 'usernamehere'@'localhost';
```
